## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - include_tasks: tasks/packages_fedora_root.yml
    - include_tasks: tasks/rustup.yml
    - include_tasks: tasks/rust_packages.yml
    - include_tasks: tasks/go_packages.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/zsh_change_user_shell_root.yml
    - include_tasks: tasks/neovim_luajit2.yml
    - include_tasks: tasks/neovim_config.yml
