---
- hosts: all
  tasks:
    - name: Clone Neovim config
      git:
        repo: https://github.com/juru1234/nvimconfig.git 
        dest: "~/.config/nvim"
        clone: yes
        accept_hostkey: yes

