## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Install Fedora Packages 
      ansible.builtin.package:
        name:
          - unzip
          - cmake
          - gettext
          - git
          - zsh
          - ripgrep
          - zoxide
          - fzf
          - eza
          - gcc
          - g++
          - openssl-devel
          - golang
          - wget
      become: yes
