
## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Install Git
      become: true
      ansible.builtin.package:
        state: present
        name: git

    - name: Install zsh
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Install ripgrep
      become: true
      ansible.builtin.package:
        state: present
        name: ripgrep

    - name: Install zoxide
      become: true
      ansible.builtin.package:
        state: present
        name: zoxide

    - name: Install fzf (command-line fuzzy finder)
      become: true
      ansible.builtin.package:
        state: present
        name: fzf
