- name: Install Fedora Packages 
  ansible.builtin.package:
    name:
      - unzip
      - cmake
      - gettext
      - git
      - zsh
      - ripgrep
      - zoxide
      - fzf
      - eza
      - gcc
      - g++
      - openssl-devel
      - golang
      - wget
      - neovim
      - kanshi
      - sway
      - waybar
      - alacritty
      - pulseaudio-utils
      - brightnessctl
  become: yes
