## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Install curl
      become: true
      ansible.builtin.package:
        state: present
        name: curl

    - name: Install RustUp
      ansible.builtin.shell: 
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
