
## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Install starship with Rust 
      ansible.builtin.shell:
        cmd: cargo install starship --locked

    - name: Copy starship.toml
      ansible.builtin.copy:
        src: starship.toml
        dest: ~/.config/starship.toml
        mode: 0644 
