## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Clone zsh autosuggestions 
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.zsh/zsh-autosuggestions
        clone: yes
        update: yes

    - name: Copy zshconfig 
      ansible.builtin.copy:
        src: zshconfig
        dest: ~/.zshrc
        mode: 0644 
