## Run locally: ansible-playbook -i localhost, playbooks/zsh.yml --connection=local -K
---
- hosts: all
  tasks: 
    - name: Clone zsh autosuggestions 
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.zsh/zsh-autosuggestions
        clone: yes
        update: yes

    - name: Install starship with cargo
      ansible.builtin.shell:
        cmd: cargo install starship --locked

    - name: Copy zshconfig
      ansible.builtin.copy:
        src: zshconfig
        dest: ~/.zshrc
        mode: 0644 
