- name: Clone zsh autosuggestions 
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/zsh-autosuggestions
    clone: yes
    update: yes

- name: Install starship with cargo
  ansible.builtin.shell:
    cmd: cargo install starship --locked
  when:
    - ansible_facts['os_family'] == "RedHat"
